version: '2'
services:
    ce-app:
        image: ce
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ce-postgresql:5432/CE
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ce-postgresql:
        extends:
            file: postgresql.yml
            service: ce-postgresql
